[project]
name = "clarity-calculator"
description = "A simple calculator smart contract for basic arithmetic operations"
authors = ["Clarity Builder"]
license = "MIT"
clarinet_version = "1.7.1"

[project.requirements]
clarinet = ">=1.0.0"

[contracts.calculator]
path = "contracts/calculator.clar"

[networks]
# Testnet configuration
testnet = { node = "https://stacks-node-api.testnet.stacks.co", accounts = [] }

# Mainnet configuration  
mainnet = { node = "https://stacks-node-api.mainnet.stacks.co", accounts = [] }

# Local development network
devnet = { node = "http://localhost:20443", accounts = [] }

[accounts.deployer]
mnemonic = "twice kind fence tip hidden tilt action fragile skin nothing balance cousin dolphin today open helmet flat boom topple door transfer inside drastic want basic"
balance = 100000000000000

[accounts.wallet_1]
mnemonic = "sell invite acquire kitten bamboo drastic seminar vivid apart fit useful modify genesis tiny toddler single want sound someone sample depth topple there sandwich"
balance = 100000000000000

[accounts.wallet_2]
mnemonic = "hold excess usual excess ring elephant install account glad dry hard pony apology feel gear feet shiver inform shy drop home jungle enough height"
balance = 100000000000000
